### ISSUE TITLE
[REQUEST] Add `LLDB`

### ISSUE THREAD

**Issue by davidroygsu** [kwk/llvm-daily-fedora-rpms#90]
Currently, installing LLDB would require downgrading.
![Screenshot from 2023-11-03 03-20-53](https://github.com/kwk/llvm-daily-fedora-rpms/assets/124539273/fbffdfaa-39e9-445f-a8cd-b3cf16c11e70)

**Comment by tuliom** [comment]
@davidroygsu what were the previous versions of `clang` and `compiler-rt`?

**Comment by davidroygsu** [comment]
> @davidroygsu what were the previous versions of `clang` and `compiler-rt`?

Every package was at version 18.

**Comment by tuliom** [comment]
Slightly related to this issue (because of the screenshot): I built llvm17-libs 17.0.4 in order to stop depending on RC4.

**Comment by kwk** [comment]
I vaguely remember that lldb sporatically failed tests in the past. I need to check back with @tstellar if we have an interest in this and can invest time in this.

**Comment by tstellar** [comment]
Can we fix this by providing newer versions of the compat libraries?

**Comment by tuliom** [comment]
> Can we fix this by providing newer versions of the compat libraries?

Let me try that. We're still missing `clang16-libs`.

**Comment by tuliom** [comment]
@tstellar It does work!

```
==============================================================================================================
 Package                     Arch   Version       Repository                                             Size
==============================================================================================================
Installing:
 lldb                        x86_64 17.0.4-1.fc40 rawhide                                               5.9 M
Installing dependencies:
 clang17-libs                x86_64 17.0.4-1.fc40 coprdep:https_download_copr_fedorainfracloud_org_results_40fedora_llvm_team_llvm_compat_packages_fedora_releasever_basearch
                                                                                                         23 M
 clang17-resource-filesystem noarch 17.0.4-1.fc40 coprdep:https_download_copr_fedorainfracloud_org_results_40fedora_llvm_team_llvm_compat_packages_fedora_releasever_basearch
                                                                                                         14 k
 llvm17-libs                 x86_64 17.0.4-1.fc40 coprdep:https_download_copr_fedorainfracloud_org_results_40fedora_llvm_team_llvm_compat_packages_fedora_releasever_basearch
                                                                                                         27 M
 python3-lldb                x86_64 17.0.4-1.fc40 rawhide                                               280 k

Transaction Summary
==============================================================================================================
Install  5 Packages
```

With that said, I'm closing this as it's now possible to install lldb on Fedora Rawhide without downgrading the packages from the snapshot repo.
Builds for other distros/architectures are still running:
https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-compat-packages/build/6604107/
